spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce  # Changed to 5432
    username: prod_username                          # Change to your prod credentials
    password: prod_password                         # Change to your prod credentials
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        maximum-pool-size: 10
        minimum-idle: 5
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true