spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/ecommerce
    username: username
    password: secret
    driver-class-name: org.postgresql.Driver  # Remove if using Spring Boot 3+
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: Mohamed  # Remove if using MailHog (not required)
    password: secret  # Remove if using MailHog
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

