cors:
  allowed-origins: "*"
  allowed-methods: "*"

spring:
  datasource:

    url:  jdbc:postgresql://postgres_sql-ecommerce:5432/ecommerce

#    jdbc:postgresql://localhost:5431/ecommerce
    # Use Docker service name
    username: username
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        maximum-pool-size: 10
        minimum-idle: 5
        format_sql: true

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true


