spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://ep-snowy-field-a2jxyy8k.eu-central-1.pg.koyeb.app/koyebdb?sslmode=require
    username: koyeb-adm
    password: npg_sjk7vf0YoicI
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        maximum-pool-size: 10
        minimum-idle: 5
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
