name: CI - Build Backend
on:
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - pom.xml
#      - docker-compose.yaml
#      - dockerfile


jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: ecommerce
        ports:
          - 5431:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build & run Unit/Integrations Tests with Maven
        run: mvn -ntp -B verify


#      - name: Set up JDK 17
#        uses: actions/setup-java@v2
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#
#      - name: Build with Maven
#        run: mvn clean install
#
#      - name: Run tests
#        run: mvn test
#
#      - name: Build Docker image
#        run: docker build -t ecommerce-app .
#
#      - name: Run Docker container
#        run: docker run --name ecommerce-app-container -d -p 8080:8080 ecommerce-app
#
#      - name: Wait for the application to start
#        run: sleep 30
#
#      - name: Run integration tests
#        run: mvn verify